/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author edilson
 */
public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        bntEmpregado = new javax.swing.JButton();
        bntFuncao = new javax.swing.JButton();
        bntRelatorioFuncao = new javax.swing.JButton();
        bntRelatorioEmpregados = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        bntCliente = new javax.swing.JButton();
        bntPedido = new javax.swing.JButton();
        bntServico = new javax.swing.JButton();
        bntRelatorioCliente = new javax.swing.JButton();
        bntRelatorioPedidos = new javax.swing.JButton();
        bntRelatorioServico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(java.awt.SystemColor.desktop);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(254, 254, 254));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LimApp");

        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Sistema de controle de funcionarios e serviços");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        bntEmpregado.setText("Cadastrar Empregado");
        bntEmpregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEmpregadoActionPerformed(evt);
            }
        });

        bntFuncao.setText("Cadastrar Função");
        bntFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntFuncaoActionPerformed(evt);
            }
        });

        bntRelatorioFuncao.setText("Relatório de Funções");
        bntRelatorioFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRelatorioFuncaoActionPerformed(evt);
            }
        });

        bntRelatorioEmpregados.setText("Relatório de Empregados");
        bntRelatorioEmpregados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRelatorioEmpregadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntRelatorioFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntEmpregado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntRelatorioEmpregados, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(193, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntEmpregado)
                    .addComponent(bntFuncao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntRelatorioFuncao)
                    .addComponent(bntRelatorioEmpregados))
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Supervisão", jPanel2);

        bntCliente.setText("Cadastrar Cliente");
        bntCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntClienteActionPerformed(evt);
            }
        });

        bntPedido.setText("Cadastro de Pedido");
        bntPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPedidoActionPerformed(evt);
            }
        });

        bntServico.setText("Cadastro de Serviço");
        bntServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntServicoActionPerformed(evt);
            }
        });

        bntRelatorioCliente.setText("Relatório de Clientes");
        bntRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRelatorioClienteActionPerformed(evt);
            }
        });

        bntRelatorioPedidos.setText("Relatório de Pedidos");
        bntRelatorioPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRelatorioPedidosActionPerformed(evt);
            }
        });

        bntRelatorioServico.setText("Relatório de Serviço");
        bntRelatorioServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRelatorioServicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntRelatorioCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bntRelatorioPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bntServico)
                    .addComponent(bntRelatorioServico))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntCliente)
                    .addComponent(bntPedido)
                    .addComponent(bntServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntRelatorioCliente)
                    .addComponent(bntRelatorioPedidos)
                    .addComponent(bntRelatorioServico))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Clientes", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntClienteActionPerformed
        // TODO add your handling code here:
        new GuiCliente().setVisible(true);
    }//GEN-LAST:event_bntClienteActionPerformed

    private void bntEmpregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEmpregadoActionPerformed
        // TODO add your handling code here:
        new GuiEmpregado().setVisible(true);
    }//GEN-LAST:event_bntEmpregadoActionPerformed

    private void bntFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntFuncaoActionPerformed
        // TODO add your handling code here:
        new GuiFuncao().setVisible(true);
    }//GEN-LAST:event_bntFuncaoActionPerformed

    private void bntPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPedidoActionPerformed
        // TODO add your handling code here:
        new GuiPedido().setVisible(true);
    }//GEN-LAST:event_bntPedidoActionPerformed

    private void bntServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntServicoActionPerformed
        // TODO add your handling code here:
        new GuiServico().setVisible(true);
    }//GEN-LAST:event_bntServicoActionPerformed

    private void bntRelatorioFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRelatorioFuncaoActionPerformed
        // TODO add your handling code here:
        new RelatorioFuncao().setVisible(true);
    }//GEN-LAST:event_bntRelatorioFuncaoActionPerformed

    private void bntRelatorioEmpregadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRelatorioEmpregadosActionPerformed
        // TODO add your handling code here:
        new RelatorioEmpregado().setVisible(true);
    }//GEN-LAST:event_bntRelatorioEmpregadosActionPerformed

    private void bntRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRelatorioClienteActionPerformed
        // TODO add your handling code here:
        new RelatorioCliente().setVisible(true);
    }//GEN-LAST:event_bntRelatorioClienteActionPerformed

    private void bntRelatorioPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRelatorioPedidosActionPerformed
        // TODO add your handling code here:
        new RelatorioPedido().setVisible(true);
    }//GEN-LAST:event_bntRelatorioPedidosActionPerformed

    private void bntRelatorioServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRelatorioServicoActionPerformed
        // TODO add your handling code here:
        new RelatorioServico().setVisible(true);
    }//GEN-LAST:event_bntRelatorioServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntCliente;
    private javax.swing.JButton bntEmpregado;
    private javax.swing.JButton bntFuncao;
    private javax.swing.JButton bntPedido;
    private javax.swing.JButton bntRelatorioCliente;
    private javax.swing.JButton bntRelatorioEmpregados;
    private javax.swing.JButton bntRelatorioFuncao;
    private javax.swing.JButton bntRelatorioPedidos;
    private javax.swing.JButton bntRelatorioServico;
    private javax.swing.JButton bntServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
